### ISSUE TITLE
Mongo Network Error

### ISSUE THREAD

**Issue by Penguin5681** [geekysamop/pinterest-clone#1]
App doesn't let me register.

error: MongoNetworkError: connect ECONNREFUSED ::1:27017, connect ECONNREFUSED 127.0.0.1:27017

**Comment by samarthmistrySM** [comment]
Hello, thanks for bringing this issue up. I think the issue you are facing is because you haven't installed the Mongo Community server. You should change the mongo connection string by registering on MondoDB atlas.

**Comment by Penguin5681** [comment]
Thanks for the Fix! Works Great. Good Job
